os: linux
dist: trusty
sudo: required
services:
  - postgresql

before_install:
  - wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04.tar.gz 
  - tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04.tar.gz
  - export PATH=swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr/bin:$PATH
  - sudo apt-get -y install libpq-dev
  - sudo apt-get -y install clang libicu-dev libkqueue-dev libtool libcurl4-openssl-dev libbsd-dev libblocksruntime-dev
  - git clone -b experimental/foundation https://github.com/apple/swift-corelibs-libdispatch.git && cd swift-corelibs-libdispatch && git submodule init && git submodule update && sh autogen.sh && ./configure --with-swift-toolchain=${PWD}/../swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr --prefix=${PWD}/../swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr && make && make install && cd ..
  - psql --help
  - psql -c 'alter user travis createdb' -U postgres
  - createdb travis
  - psql -c 'create user todolist' -U postgres
  - createdb todolist
  - psql -c 'grant postgres to travis' -U postgres
  - psql -c 'grant postgres to todolist' -U postgres
  - psql -c '\c todolist' -U todolist
  - psql -c 'create table todos(tid BIGSERIAL PRIMARY KEY, user_id varchar(128) NOT NULL, title varchar(256) NOT NULL, completed boolean NOT NULL, ordering INTEGER NOT NULL);' -U todolist
  - psql -c 'grant all privileges on todos to public' -U todolist
  - git clone https://github.com/IBM-Swift/todolist-tests Tests

script:
  - swift build -Xcc -fblocks -Xcc -I/usr/include/postgresql -Xlinker -rpath -Xlinker .build/debug  
  - swift test
